### ISSUE TITLE
can it support Chinese or non-english 

### ISSUE THREAD

**Issue by dongxiaohuang** [seperman/fast-autocomplete#18]
I found it fail to search for non-english words

**Comment by seperman** [comment]
Yes, I need to double check and see if the Levenshtein distance library Im using can take none ASCII characters. Then I can make it work with Unicode.

Sep Dehpour

**Comment by Bhee** [comment]
Any updates? Whether it works for unicode string?

**Comment by seperman** [comment]
Hi @Bhee 
I just published 0.7.0 which allows you to pass the unicode characters that are acceptable to Autocomplete:
https://github.com/seperman/fast-autocomplete#unicode

**Comment by seperman** [comment]
Also @dongxiaohuang
