### ISSUE TITLE
How to use display names?

### ISSUE THREAD

**Issue by prasadgsk-mindtree** [seperman/fast-autocomplete#19]
Would you pls help as how to use display names?

**Comment by aakash-tanwar** [comment]
@seperman I also have the same question, about using display names and context in suggestions. Kindly share some examples/process through we can implement that.

**Comment by seperman** [comment]
Hi @aakash-tanwar and @prasadgsk-mindtree 
I added an example in the readme:

```py
>>> autocomplete.words['acura']
WordValue(context={'make': 'acura'}, display='Acura', count=130123, original_key=None)
>>> autocomplete.words['acura'].display
Acura
```
