### ISSUE TITLE
fast-autocomplete separates words with a dash ('-') symbol.

### ISSUE THREAD

**Issue by wgbusch** [seperman/fast-autocomplete#24]
Hi, i've been using fast autocomplete for my project and so far I'm quite happy with it, but I found something very annonying:

some of the words of my dictionary have a dash, like for example 'ASB-E'. When I search for 'ASB-E', I don't get tthe exact math of 'ASB-E',  autocomplete seems to assume that the dash is a word separator and  I get this result:

![image](https://user-images.githubusercontent.com/29581073/112373868-32debe00-8cc0-11eb-936a-a14130bd4576.png)

Is there any fix to it? I would like to make autocomplete treat the dash as just another letter. Thank you.

**Comment by seperman** [comment]
Hi, thanks.
Off the top of my head, you should add dash as a character that it accepts. Examples are here: https://github.com/seperman/fast-autocomplete#unicode

Sep Dehpour

**Comment by seperman** [comment]
Hi @wgbusch 
Seems like that must have solved the problem for you.
