### ISSUE TITLE
Double results when start of synonym matches start of another word

### ISSUE THREAD

**Issue by AndreaSottana** [seperman/fast-autocomplete#25]
Hello,

Not sure if this is a bug or a wanted behaviour, but I would be grateful if you could explain why this is happening. See this small reproducible example below.

```
from fast_autocomplete import AutoComplete

words = {'collision': {}, 'collateral': {}}
synonyms = {'collateral': ['coll']}
autocomplete = AutoComplete(words=words, synonyms=synonyms)
print(autocomplete.search(word='coll'))
```

The output is
> [['collateral'], ['collateral', 'collision']] 

Why is "collateral" repeated twice, and why are there two nested lists, one with one element and one with two elements? Does it mean that words within the inner list are closer to each other?
Any insight much appreciated!

**Comment by seperman** [comment]
Hi,
Yes the nested list output is intended. The words that have the same “distance” from the input will be grouped together in a list.

You don’t need to add a synonym that is literally a prefix of another word. That’s why you are getting that word twice. Synonyms are for words that are different but have the same meaning like “car” and “vehicle”.

Sep Dehpour

**Comment by AndreaSottana** [comment]
Thanks @seperman !

**Comment by AndreaSottana** [comment]
Actually, could you please explain the following behaviour as well which is a bit confusing? @seperman 
```
from fast_autocomplete import AutoComplete

words = {'cartoon': {}, 'vehicle': {}}
synonyms = {'vehicle': ['car']}
autocomplete = AutoComplete(words=words, synonyms=synonyms)
print(autocomplete.search(word='ca'))
```

This returns only
> [['vehicle']]

but it doesn't return "cartoon". How would you explain this?
Thanks again

**Comment by seperman** [comment]
@AndreaSottana interesting, let me take a look.

**Comment by seperman** [comment]
This is a bug.

**Comment by seperman** [comment]
@AndreaSottana Thanks for bringing this bug into my attention.
It is fixed now. Here is a test based on your case:
https://github.com/seperman/fast-autocomplete/blob/master/tests/test_autocomplete.py#L104

**Comment by seperman** [comment]
Fast Autocomplete 7.0.2 is released.

**Comment by AndreaSottana** [comment]
Great, thanks for letting me know @seperman and thanks for fixing the bug so quickly!
