### ISSUE TITLE
team up with komorebi a windows manager also micro text editor for windows.

### ISSUE THREAD

**Issue by XxnittanixX** [seperman/fast-autocomplete#31]
reason why is because i beleive  that  auto complete  in the terminal should not be so hard to complete  i started and never finished on a project like this  using python  but never got far so im hoping you can take it further than i did

**Comment by seperman** [comment]
Hi @XxnittanixX 
Not sure who is behind Komerobi. I have not used Microsoft Windows in many years. I'm not sure if I can help here.
